version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1000:80"
    volumes:
      - .:/var/www/html
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: bank-project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3640

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: bank-project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3640
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
